### ISSUE TITLE
Change the "configure for" settings

### ISSUE THREAD

**Issue by yutzuch** [dahall/TaskScheduler#11]
Hi.
I have a simple question but I couldn't find the solution.
What's the code if I want to change the "configure for" settings?
e.g. Windows Vista -> Windows 10

**Comment by dahall** [comment]
That is tied to the TaskDefinition.Settings.Compatibility property. Please not however, that the UI will analyze the settings and will display the lowest compatible OS version.

**Comment by yutzuch** [comment]
Thanks for your explanation!
But what's the difference between V2_2 and V2_3 cause I have the same result(Windows 10) while using these two.

**Comment by dahall** [comment]
In almost every version of Windows since Vista, Microsoft has released new capabilities for the native Task Scheduler. They increment the minor version number each time. Depending on which of those new features you use, the compatibility value will show which is the least compatible version of the library that will support those properties. Windows 8.1 and early 10 releases supported 2.2 where later versions of Win 10 are 2.3. Most of this is not documented by Microsoft.
