### ISSUE TITLE
Class already exists in mscorlib

### ISSUE THREAD

**Issue by middas** [dahall/TaskScheduler#15]
In Visual Studio 2017 running under .NET 4.5, trying to move from TaskScheduler 2.5.20 to the latest or even the next build up throws the following error on build attempt:
CS0433  C# The type exists in both and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

The class it's referring to is IReadOnlyCollection<T>. Looking at your source code, I see conditional statements; however, it looks like those are not functional.

**Comment by dahall** [comment]
This is only a problem when you are building against a .NET version over 4.5 but below 4.5.2. The NuGet package includes a 4.0 and 4.5.2 version of the library. When you build against 4.5 or 4.5.1, NuGet will select the 4.0 library and you'll see this error. If you change your build to either 4.5.2 or 4.0, this problem goes away. It exists because Microsoft introduced the new interfaces in 4.5 and the library re-creates them in prior .NET builds for compatibility.
