### ISSUE TITLE
Settings.Priority property not Granular Enough

### ISSUE THREAD

**Issue by ixm7** [dahall/TaskScheduler#49]
How can we set the Priority property to a precise level (for example, 4).
Assigning 'Normal' to the Settings.Priority property is using '5' as the level. But what if we need to set it to 4?
Trying to change td.XmlText doesn't produce any effect. 
td.Settings.XmlText comes back as unimplemented property.

**Comment by dahall** [comment]
What OS is the library being run from and is it connecting remotely to another system with a different OS?

**Comment by dahall** [comment]
Actually, it doesn't matter. I just looked at the code and I didn't leave a backdoor to allow setting the actual value. I'd be happy to look at that as an enhancement request though.

**Comment by ixm7** [comment]
Thanks!

**Comment by dahall** [comment]
I've just committed an update that allows a precise value to be set. Without breaking existing code, there is not a way to get it on retrieval. You'd need to look at the XML.

Setting the value granularly can be done as follows in the next release (2.7.3):
```
td.Settings.Priority = (ProcessPriorityClass)4;
```
Having used this library thousands of times since Windows Vista was released and it was introduced, I've never found a reason to be granular when using this value. I'm curious as to what your use case is.

**Comment by ixm7** [comment]
That was blazing fast response; Many thanks!!! 

Use case: need to set to 4 instead of 5 (which gets set by assigning Normal).
4 Allows MemoryPriority (not just ProcessPriority) to be the same as Interactive process.

Yes, I already use the XmlText property to get the current granular priority value.

Again, many thanks!
