### ISSUE TITLE
TaskSchedulerEditor COM-Visible

### ISSUE THREAD

**Issue by alexdyb** [dahall/TaskScheduler#5]
Hi,
can you make TaskSchedulerEditor.dll COM-Visible? I am trying to use it from VBA, Microsoft.Win32.TaskScheduler.dll works fine, but not Microsoft.Win32.TaskSchedulerEditor.dll.

Thanks
Alex

**Comment by dahall** [comment]
I have added that switch to the build. It will appear in the next release.

**Comment by dahall** [comment]
Testing of this change has gone poorly. You must not be using Microsoft.Win32.TaskScheduler.dll because it does not have COM enabled. You are likely using the Microsoft objects directly. Enabling COM, while possible, doesn't produce good results due to a number of .NET specific method arguments and return values that are not supported under COM (generic collections, explicit structure layouts, non-COM types, etc.). The amount of rework required and the fact that I would have to change well established APIs makes this request too difficult for implementation. My apologies.

**Comment by alexdyb** [comment]
Well, I think i am sure i use Microsoft.Win32.TaskScheduler.dll for simple calls, but you are right about types that are not supported under COM, perhaps this is a reason TaskSchedulerEditor.dll not working. I will make a wrapper dll. Thanks, you made a great job!
