### ISSUE TITLE
How to pass parameters in Task.Run

### ISSUE THREAD

**Issue by RevealedFrom** [dahall/TaskScheduler#799]
I need help in understanding the part in the [documentation](https://dahall.github.io/TaskScheduler/html/M_Microsoft_Win32_TaskScheduler_Task_Run.htm) which says the following about the arguments passed to `Task.Run(parameters)`:

>These values can be used in the task action where the $(ArgX) variables are used in the action properties. 

I tried passing in a small array of strings, and I had a look at `RunningTask.Xml` and the arguments were not in there. The actual program when executed also did not receive the arguments.

In the Xml I can see only the arguments that are hardcoded in the Windows Task Scheduler UI.

Must I take any additional actions in order to inject the arguments into the action?

Also, what if there are more than one action, how are the arguments distributed out?

**Comment by dahall** [comment]
See the documentation [here](https://docs.microsoft.com/en-us/windows/desktop/api/taskschd/nf-taskschd-iregisteredtask-run) from Microsoft. I've updated the project documentation with this information for the future. Let me know if you have questions after reviewing the above.

**Comment by RevealedFrom** [comment]
Urgh, don't know any C++!

I am stumped on what the $(ArgX) refer to. If I understand them as the arguments passed to a program, then aren't they just available for the program to consume?  I called `task.Run(new string[] { "abc", "123" });`, but my task action, a console app, doesn't see two arguments. Besides invoking the `Run` method do I have to do anything else?

**Comment by dahall** [comment]
First and foremost, the $(ArgX) string syntax is only used when calling items from Task.Run or Task.RunEx. They actually can cause failures if a trigger runs the action and the executable doesn't know to omit them when not provided. Only the EventTrigger knows how to pass variables when running a trigger. Hopefully this brief sample will help:

Create a task that has the $(ArgX) items placed in the ExecAction:
```cs
var td = ts.NewTask();
td.Actions.Add(new ExecAction("cmd", "$(Arg0) $(Arg1) $(Arg2) $(Arg3)", null));
var t = ts.RootFolder.RegisterTaskDefinition("Test", td);
```
You'll see here that there is no trigger as any trigger would run the following as if from the command line:
```
cmd $(Arg0) $(Arg1) $(Arg2) $(Arg3)
```
Since these parameter values are just gibberish to cmd.exe, you'd see errors.

Instead, if you were to use the Run method as follows,
```cs
t.Run("/K", "ECHO", "I said to Fred,", "\"Hello to you\"");
// Notice you don't need to create a string array since its passed with the params keyword
```
you'd get the effect of running the following from the command line with the variables replaced:
```
cmd ECHO I said to Fred, "Hello to you"
```
So far, not very interesting. However the EventTrigger does allow you to capture variables and pass them to Action properties at trigger execution time. More information can be found [here](https://docs.microsoft.com/en-us/windows/desktop/TaskSchd/eventtrigger-valuequeries). So instead of the code above, you could do something like the following which would call the parameters from a trigger:
```cs
var td = ts.NewTask();
td.Actions.Add(new ExecAction("cmd", "ECHO The user name was $(user)", null));
var et = new EventTrigger { Subscription = "[some valid XPath query]"};
et.ValueQueries["user"] = "Event/UserData/SubjectUserName";
td.Triggers.Add(et);
var t = ts.RootFolder.RegisterTaskDefinition("Test", td);
```
Here, when the event described in the event `Subscription` fires, it will grab the value described in the `ValueQueries` and pass that to the ExecAction.

**Comment by dahall** [comment]
Please note that all of the above is based on my reading of the documentation. I have not ever tried this and could not find any example of it online or in any of my test machines actual tasks.

**Comment by RevealedFrom** [comment]
Thank you for the detailed example. I am sorry I didn't describe more about my use case. 

I am using your library to get an existing task (that was configured by the Windows Task Scheduler Desktop App UI) and then running it. I am not creating tasks programmatically.

The reason I am doing this because the triggering of the task is done from a web page. So it is the web server code (ASP.NET MVC) that is calling `GetTask()` and then `Run`ning it. I couldn't use the usual `System.Diagnosis.Processs.Start` because the job that is triggered will take hours to run, and I have to return the web page to the user.

So it would be great to be able to pass parameters to the job that is triggered. If not, I would just use a file to pass the dynamic arguments.

**Comment by dahall** [comment]
So you would like to execute the task's actions (commands) asynchronously?

**Comment by RevealedFrom** [comment]
That is correct.

I am using a Scheduled Task not for the purpose of having it triggered at specified times, but for `Run`ning it on demand from a web page.

So far your library is working very well other than I don't know how to pass parameters to the Action (my Scheduled Task has only one action configured).

**Comment by dahall** [comment]
In that case, you would follow the first example I gave above. In the ExecAction, you would have the $(ArgX) entries for each unique argument you need passed to the executable. To make it really simple, just have $(Arg0) there and then pass the full argument string as the first and only string to the Run method.
```cs
// To create the action
new ExecAction("[Full path to exe here]", "$(Arg0)", null);
// --- Make sure there are no triggers on the task

// From other code to run the task
var task = TaskService.Instance.GetTask("[Your task name here]");
task.Run("big long string of all the parameters to pass");
```

**Comment by RevealedFrom** [comment]
The part I am still confused is: the task returned from `GetTask` already has an action configured. What does `new ExecAction` do to my configured action?

**Comment by dahall** [comment]
You would need to modify the existing ExecAction to add the argument indicator
