### ISSUE TITLE
TaskService ImportTask

### ISSUE THREAD

**Issue by GromitD90** [dahall/TaskScheduler#817]
I am making the following call to Import a scheduled task from an xml file.
TaskService.Instance.RootFolder.ImportTask(taskname, item);

This works even if a scheduled task by the name taskname already exists. The old task is just deleted and overwritten with the new one.

Is this expected behaviour? Is there any way to determine if such an event has occurred?

Importing a task manually to the task scheduler does alert you to the fact that a task already exists.

Apologies if this should not have used the bug reporting process

**Expected behavior**
I would expect that the ImportTask method would return an error code

**Screenshots**

**Environment (please complete the following information):**
 - Host Windows version - Windows 10 Home 1903
 - Library version: 2.8.13

**Additional context**

**Comment by dahall** [comment]
This is a good callout. Thanks! Unintended consequences is a bad model. As such, I have added a boolean parameter to the end of the `ImportTask` called `overwriteExisting` and set its default so that it behaves the same as the current implementation. However, for your purposes, it should allow you to capture the condition where the task already exists and will throw an exception. Code is committed and will be included in 2.8.14 after testing completes.

**Comment by GromitD90** [comment]
Thank you for such a fast response. This is what I call awesome support.

**Comment by dahall** [comment]
You're welcome. I think under 30 minutes is a record for me. The stars aligned with me getting your email when it arrived, being in front of my dev station, and finding an easy fix.
