### ISSUE TITLE
Serialization Error in TaskDefinition

### ISSUE THREAD

**Issue by PapaZito** [dahall/TaskScheduler#824]
I'm trying to save a TaskDefinition to the ViewState so I can persist it across postbacks on an asp.net web page.  However, it's throwing the following when I do so:

Type 'Microsoft.Win32.TaskScheduler.TaskDefinition' in Assembly 'Microsoft.Win32.TaskScheduler, Version=2.8.15.0, Culture=neutral, PublicKeyToken=c416bc1b32d97233' is not marked as serializable.

Looking at the code, TaskDefinition implements IXmlSerializable so I'm not sure why it's throwing this.  Maybe the class needs the [Serializable] tag?

**Comment by dahall** [comment]
Do you know the requirements for an object in order for it to be saved to `ViewState`? I'm not familiar with that. If you can find them and post them, I can try to make `TaskDefinition` comply.

**Comment by PapaZito** [comment]
So my workaround for this was to create my own set of Trigger classes that essentially mirror the ones in the library, but only include the properties like StartBoundary etc.  Then on the last step I loop my list and create the TaskScheduler versions.  To persist my objects in the ViewState all I ended up having to do was set the [Serializable] tag for the class.  

Here's a StackOverflow discussion on the topic: https://stackoverflow.com/questions/3583573/which-types-of-objects-can-we-place-in-view-state

**Comment by dahall** [comment]
The `TaskDefinition.XMLText` value contains a complete dump of all settings which can easily be put back into a new `TaskDefinition`. I'll look at what it would take to effectively make `TaskDefinition` serializable using nothing but that XML output. While you're waiting for me to get that done, rather than maintain a whole code base for triggers, you could just persist that XML as a string in ViewState.

**Comment by dahall** [comment]
Just getting to updating the library and I have a question: How are you associating the next `TaskDefinition` with the current `TaskService` instance? When implementing ISerializable one has to provide a constructor that will deserialize the object. Unfortunately, there is no way I can see to associate this random deserialized definition with its parent `TaskService` so that it can actually be created on a system. What is your workflow?

**Comment by dahall** [comment]
There is really no way to this without significant architectural changes. I'm glad there is a working solution.

**Comment by kaizenn17** [comment]
buenas, cada vez que prendo mi pc me sale este error
![Sin título](https://user-images.githubusercontent.com/72838146/95924614-4c352300-0d8e-11eb-8578-ae7bc1993157.jpg)

si tienen idea de como solucionar este error, me ayudarian demaciado, por favor
